### ISSUE TITLE
ubuntu环境下需要修改两个地方

### ISSUE THREAD

**Issue by xiakunhou** [nikoloss/linuxstuff#1]
1. sh 在ubuntu下默认指向的是dash,　和bash语法有很多不一致。
需要将第一行的声明改成:
`#!/bin/bash`

2. `Unity` 和 `Gnome Shell`环境下使用的`gsettings`设置背景，
需要将背景修改的那一行代码:
`pcmanfm -w `pwd`/dest.jpg`
修改为：
`gsettings set org.gnome.desktop.background picture-uri "file://"`pwd`/dest.jpg`

**Comment by nikoloss** [comment]
感谢您的分享，不过此项目是依托专栏的文章的发表而演进的，只作为文章的辅助说明。如果您是其他发行版的用户，那可能需要您自行修改源码了。非常感谢您的关注
